# Generated by Django 6.0.3 on 2026-04-05 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('logo', models.ImageField(upload_to='homepage/clients/')),
                ('website_url', models.URLField(blank=True)),
                ('row', models.PositiveSmallIntegerField(default=1, help_text='Use 1 or 2 for slider row.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['row', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FeatureItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='bi bi-check2-square', max_length=80)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FooterLinkGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('subtitle_badge', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='homepage/hero/')),
                ('primary_button_text', models.CharField(blank=True, max_length=100)),
                ('primary_button_url', models.CharField(blank=True, default='#', max_length=255)),
                ('secondary_button_text', models.CharField(blank=True, max_length=100)),
                ('secondary_button_url', models.CharField(blank=True, default='#', max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HomePageSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site_title', models.CharField(default='Muzadi Technologies - Innovate, Integrate, Inspire', max_length=255)),
                ('meta_keywords', models.TextField(blank=True, default='Muzadi Technologies, Uganda IT company, software development, web development, mobile apps, system development, Kampala tech company')),
                ('meta_description', models.TextField(blank=True, default='Muzadi Technologies is a leading IT company in Uganda offering software development, web design, mobile apps, and digital solutions to help businesses grow.')),
                ('meta_author', models.CharField(blank=True, default='Muzadi Technologies', max_length=255)),
                ('company_name', models.CharField(default='Muzadi Technologies', max_length=255)),
                ('tagline', models.CharField(default='Innovate • Integrate • Inspire', max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='homepage/branding/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='homepage/branding/')),
                ('phone_number', models.CharField(blank=True, default='+256784103296', max_length=50)),
                ('whatsapp_number', models.CharField(blank=True, default='+256784103296', max_length=50)),
                ('email', models.EmailField(blank=True, default='info@muzaditechnologies.com', max_length=254)),
                ('website_url', models.URLField(blank=True, default='https://www.muzaditechnologies.com')),
                ('address', models.CharField(blank=True, default='Kampala, Uganda', max_length=255)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('intro_badge', models.CharField(default='Who We Are', max_length=120)),
                ('intro_heading', models.CharField(default='Building smart digital solutions for modern businesses', max_length=255)),
                ('intro_text_1', models.TextField(default='Muzadi Technologies is a Uganda-based technology company focused on building modern, scalable and secure digital solutions for organizations, startups, schools and growing enterprises.')),
                ('intro_text_2', models.TextField(default='We help businesses move from manual processes to intelligent systems through custom software development, mobile applications, websites, automation tools, branding and digital transformation services.')),
                ('services_title', models.CharField(default='Our Services', max_length=120)),
                ('services_subtitle', models.CharField(default='Premium technology services tailored for modern businesses', max_length=255)),
                ('products_title', models.CharField(default='Software Products', max_length=120)),
                ('products_subtitle', models.CharField(default='Powerful solutions we build for businesses, schools and organizations', max_length=255)),
                ('features_title', models.CharField(default='Why Choose Us', max_length=120)),
                ('features_subtitle', models.CharField(default='What makes Muzadi Technologies a strong technology partner', max_length=255)),
                ('features_image', models.ImageField(blank=True, null=True, upload_to='homepage/features/')),
                ('pricing_title', models.CharField(default='Pricing', max_length=120)),
                ('pricing_subtitle', models.CharField(default='Flexible packages for different business needs', max_length=255)),
                ('clients_title', models.CharField(default='Our Clients', max_length=120)),
                ('clients_subtitle', models.CharField(default='Trusted by growing businesses, schools and organizations', max_length=255)),
                ('clients_intro', models.TextField(blank=True, default='We partner with institutions and businesses across different sectors to build reliable digital solutions that improve efficiency, service delivery and growth.')),
                ('clients_note', models.TextField(blank=True, default='From startups to established institutions, we deliver digital products that are practical, scalable and built for real operational impact.')),
                ('cta_badge', models.CharField(default='Let’s Build Something Great', max_length=120)),
                ('cta_heading', models.CharField(default='Ready to transform your idea into a powerful digital solution?', max_length=255)),
                ('cta_text', models.TextField(default='Whether you need a website, mobile app, school system, business platform or custom software solution, Muzadi Technologies is ready to help.')),
                ('cta_button_text', models.CharField(default='Start a Project', max_length=100)),
                ('cta_button_url', models.CharField(default='#contact', max_length=255)),
                ('cta_whatsapp_text', models.CharField(default='Chat on WhatsApp', max_length=100)),
                ('footer_about', models.TextField(default='We build modern websites, business systems, mobile apps and digital solutions that help organizations work smarter and grow faster.')),
                ('footer_copyright', models.CharField(default='© 2026 Muzadi Technologies. All Rights Reserved.', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IntroPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=255)),
                ('icon', models.CharField(default='bi bi-check-circle-fill', max_length=80)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='IntroStatCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('price_prefix', models.CharField(blank=True, default='From', max_length=50)),
                ('currency', models.CharField(blank=True, default='UGX', max_length=20)),
                ('price_text', models.CharField(default='800K+', max_length=100)),
                ('icon', models.CharField(default='bi bi-rocket-takeoff', max_length=80)),
                ('button_text', models.CharField(default='Request Package', max_length=100)),
                ('button_url', models.CharField(default='#contact', max_length=255)),
                ('featured_label', models.CharField(blank=True, max_length=120)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='homepage/services/')),
                ('icon', models.CharField(default='bi bi-window-stack', max_length=80)),
                ('item_1', models.CharField(blank=True, max_length=150)),
                ('item_2', models.CharField(blank=True, max_length=150)),
                ('item_3', models.CharField(blank=True, max_length=150)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SoftwareProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='homepage/products/')),
                ('icon', models.CharField(default='bi bi-box', max_length=80)),
                ('tag', models.CharField(blank=True, max_length=120)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=120)),
                ('url', models.CharField(default='#', max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='mainapp.footerlinkgroup')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PricingPlanFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='mainapp.pricingplan')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
