# Generated by Django 6.0.3 on 2026-04-15 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_receipt_receiptitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='due_date',
        ),
        migrations.AlterField(
            model_name='receipt',
            name='status',
            field=models.CharField(choices=[('PAID', 'Paid'), ('PARTIAL', 'Partial'), ('PENDING', 'Pending'), ('CANCELLED', 'Cancelled')], default='PAID', max_length=20),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='terms',
            field=models.TextField(blank=True, default='Thank you for your business.'),
        ),
    ]
