# Generated by Django 6.0.3 on 2026-04-15 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_invoice_homepagesetting_authorized_signature_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='amount_paid',
            new_name='amount_received',
        ),
        migrations.RenameField(
            model_name='receipt',
            old_name='client_address',
            new_name='payer_address',
        ),
        migrations.RenameField(
            model_name='receipt',
            old_name='client_email',
            new_name='payer_email',
        ),
        migrations.RenameField(
            model_name='receipt',
            old_name='client_phone',
            new_name='payer_phone',
        ),
        migrations.RenameField(
            model_name='receipt',
            old_name='issued_date',
            new_name='payment_date',
        ),
        migrations.RenameField(
            model_name='receipt',
            old_name='client_name',
            new_name='received_from',
        ),
        migrations.RenameField(
            model_name='receiptitem',
            old_name='unit_price',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='tax_percentage',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='terms',
        ),
        migrations.RemoveField(
            model_name='receiptitem',
            name='quantity',
        ),
        migrations.AddField(
            model_name='receipt',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='mainapp.invoice'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank Transfer'), ('MOBILE', 'Mobile Money'), ('CHEQUE', 'Cheque'), ('OTHER', 'Other')], default='BANK', max_length=20),
        ),
        migrations.AddField(
            model_name='receipt',
            name='reference_number',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='status',
            field=models.CharField(choices=[('ISSUED', 'Issued'), ('VOID', 'Void')], default='ISSUED', max_length=20),
        ),
    ]
